// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxnIkOmKGzuItp9yu1bqjt0EB0gT_fv8',
    appId: '1:314657496270:web:f50bf0a138a8ab4683849f',
    messagingSenderId: '314657496270',
    projectId: 'estore-2b90f',
    authDomain: 'estore-2b90f.firebaseapp.com',
    storageBucket: 'estore-2b90f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDroL9Q7h4j4qZ3eUIoBcTk0OSsUUtu_os',
    appId: '1:314657496270:android:cff3425c99a1302083849f',
    messagingSenderId: '314657496270',
    projectId: 'estore-2b90f',
    storageBucket: 'estore-2b90f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHclZmOl0P27Z39G5bDEDAy2pCiaIw6sw',
    appId: '1:314657496270:ios:9a7b6476cfe8028483849f',
    messagingSenderId: '314657496270',
    projectId: 'estore-2b90f',
    storageBucket: 'estore-2b90f.appspot.com',
    iosClientId:
        '314657496270-ducbflo6rb7g9pa9fhq3942g07s83rfm.apps.googleusercontent.com',
    iosBundleId: 'com.quantec.estore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHclZmOl0P27Z39G5bDEDAy2pCiaIw6sw',
    appId: '1:314657496270:ios:274d0589564757b283849f',
    messagingSenderId: '314657496270',
    projectId: 'estore-2b90f',
    storageBucket: 'estore-2b90f.appspot.com',
    iosClientId:
        '314657496270-u597tkpguiv1gi268477i3hfacb1lsoh.apps.googleusercontent.com',
    iosBundleId: 'com.quantec.estore.RunnerTests',
  );
}
